// Generated by https://quicktype.io

export interface Project {
  id:              string;
  project_name:    string;
  duration_months: number;
  department:      string;
  percentage:      number;
  project_state:   string;
}
