// Generated by https://quicktype.io

export interface Project {
  id_project:      number;
  id_department:   number;
  name_project:    string;
  duration_months: number;
  state_project:   string;
  xxx_percentage:      number;
  xxx_department:   string;
}
