// Generated by https://quicktype.io

export interface Project {
  id:              number;
  id_department:   number;
  project_name:    string;
  duration_months: number;
  percentage:      number;
  project_state:   string;
  xxx_department:   string;
}
